### ISSUE TITLE
感谢分享这么好的代码，但是有个问题想请教下

### ISSUE THREAD

**Issue by 1xiaocainiao** [cooxu/PresentAnimView#1]
我通过im收到礼物消息，是一条一条的，我看了你demo里面，假数据的礼物数量是写死了的5个，8个礼物这种，那么我通过im的话就只能自己再次计数了，有什么好的解决办法吗

**Comment by 1806339272** [comment]
感谢你的分享，但是下载的代码运行报错，缺少IJKMediaFramework.framework静态库

**Comment by cooxu** [comment]
@1806339272  demo不依赖IJKMediaFramework.framework静态库，应该是你的直播程序缺少这个文件，参考SunLiner/MiaowShow，http://www.jianshu.com/p/b8db6c142aad ， 里面有IJKMediaFramework.framework的打包教程和下载地址

**Comment by cooxu** [comment]
@1xiaocainiao 谢谢支持！“通过im的话就只能自己再次计数” 这个我不太理解您的意思。我们项目的流程是这样：一旦有人送礼物，服务端接收消息后，客户端就会触发类似- (void)OnChat:(NSArray*)chatArray 回调，遍历 chatArray 解析成礼物模型，这个礼物模型也就是 demo 中的GiftModel，模型里面就有礼物数量，送礼物人的信息等，然后给 AnimOperation.model 赋值，执行动画队列。

**Comment by 1xiaocainiao** [comment]
我们送礼的model没有包含礼物数量，或者是始终为1，做连发的时候就造成了每次收到消息，就触发一次动画，但是确不会有连击；所以是否只能自己在做连发发送消息的时候，计数一次呢，就像demo中一样，有个giftCount 计数

**Comment by cooxu** [comment]
@1xiaocainiao 嗯，那你只能对 demo 进行改造了，如果就一列视图的话，把最大并发数和控制 frame 的 的 index % 2 都改为1；把动画视图做成单例，避免了收到消息重复创建视图，单例里面添加个 giftCount 计数；然后你还需要对动画进行修改，把动画结束的条件改成你们自己的逻辑，希望对你有帮助～

**Comment by 1xiaocainiao** [comment]
感谢提供思路
